const fs = require('fs');
const lines = [
  "'use client';",
  "",
  "import Link from 'next/link';",
  "import { useState } from 'react';",
  "",
  "export default function Navbar() {",
  "  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);",
  "",
  "  const toggleMobileMenu = () => {",
  "    setIsMobileMenuOpen(!isMobileMenuOpen);",
  "  };",
  "",
  "  return (",
  "    <nav className=\"bg-white shadow-md border-b-4 border-accent relative z-50\">",
  "      <div className=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">",
  "        <div className=\"flex justify-between h-20\">",
  "          <div className=\"flex items-center\">",
  "            <Link href=\"/\" className=\"flex-shrink-0 flex items-center\">",
  "              <span className=\"font-bold text-2xl text-primary tracking-tight\">St. Theresa School</span>",
  "            </Link>",
  "          </div>",
  "          ",
  "          {/* Desktop Menu */}",
  "          <div className=\"hidden md:flex md:items-center md:space-x-8\">",
  "            <Link href=\"/\" className=\"text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Home</Link>",
  "            <Link href=\"/about\" className=\"text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">About Us</Link>",
  "            <Link href=\"/academics\" className=\"text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Academics</Link>",
  "            <Link href=\"/admissions\" className=\"text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Admissions</Link>",
  "            <Link href=\"/gallery\" className=\"text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium transition-colors\">Gallery</Link>",
  "            <Link href=\"/cbse-disclosure\" className=\"bg-primary text-white hover:bg-primary-light px-4 py-2 rounded-md text-sm font-medium transition-colors shadow-sm\">CBSE Mandatory Disclosure</Link>",
  "          </div>",
  "",
  "          {/* Mobile Menu Button */}",
  "          <div className=\"flex items-center md:hidden\">",
  "            <button ",
  "              type=\"button\" ",
  "              className=\"text-gray-700 hover:text-primary focus:outline-none p-2\"",
  "              onClick={toggleMobileMenu}",
  "              aria-label=\"Toggle mobile menu\"",
  "            >",
  "              <svg className=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">",
  "                {isMobileMenuOpen ? (",
  "                  <path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M6 18L18 6M6 6l12 12\" />",
  "                ) : (",
  "                  <path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth={2} d=\"M4 6h16M4 12h16M4 18h16\" />",
  "                )}",
  "              </svg>",
  "            </button>",
  "          </div>",
  "        </div>",
  "      </div>",
  "",
  "      {/* Mobile Menu Panel */}",
  "      {isMobileMenuOpen && (",
  "        <div className=\"md:hidden bg-white border-t border-gray-100 absolute w-full shadow-lg\">",
  "          <div className=\"px-2 pt-2 pb-4 space-y-1 sm:px-3\">",
  "            <Link href=\"/\" onClick={toggleMobileMenu} className=\"block text-gray-700 hover:text-primary hover:bg-gray-50 px-3 py-2 rounded-md text-base font-medium\">Home</Link>",
  "            <Link href=\"/about\" onClick={toggleMobileMenu} className=\"block text-gray-700 hover:text-primary hover:bg-gray-50 px-3 py-2 rounded-md text-base font-medium\">About Us</Link>",
  "            <Link href=\"/academics\" onClick={toggleMobileMenu} className=\"block text-gray-700 hover:text-primary hover:bg-gray-50 px-3 py-2 rounded-md text-base font-medium\">Academics</Link>",
  "            <Link href=\"/admissions\" onClick={toggleMobileMenu} className=\"block text-gray-700 hover:text-primary hover:bg-gray-50 px-3 py-2 rounded-md text-base font-medium\">Admissions</Link>",
  "            <Link href=\"/gallery\" onClick={toggleMobileMenu} className=\"block text-gray-700 hover:text-primary hover:bg-gray-50 px-3 py-2 rounded-md text-base font-medium\">Gallery</Link>",
  "            <Link href=\"/cbse-disclosure\" onClick={toggleMobileMenu} className=\"block mt-4 bg-primary text-white hover:bg-primary-light px-4 py-2 rounded-md text-base font-medium text-center\">CBSE Mandatory Disclosure</Link>",
  "          </div>",
  "        </div>",
  "      )}",
  "    </nav>",
  "  );",
  "}"
];
fs.writeFileSync('src/components/Navbar.tsx', lines.join('\\n'));
